# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Miles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Miles
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Google'
pod 'FirebaseFirestoreSwift'
pod 'FirebaseUI'
end
